from app.prompts.essay_feedback import ESSAY_FEEDBACK_PROMPT
from app.prompts.revision_feedback import ESSAY_REVISION_COMPARISON_PROMPT
from app.prompts.sentence_challenge import (
    SENTENCE_CHALLENGE_FEEDBACK_PROMPT,
    SENTENCE_CHALLENGE_GENERATION_PROMPT,
)
from app.prompts.sentence_feedback import SENTENCE_UPGRADE_FEEDBACK_PROMPT

__all__ = [
    "ESSAY_FEEDBACK_PROMPT",
    "ESSAY_REVISION_COMPARISON_PROMPT",
    "SENTENCE_CHALLENGE_FEEDBACK_PROMPT",
    "SENTENCE_CHALLENGE_GENERATION_PROMPT",
    "SENTENCE_UPGRADE_FEEDBACK_PROMPT",
]
